### ISSUE TITLE
书源没法导入

### ISSUE THREAD

**Issue by ggtony233** [hectorqin/reader#112]
以下是日志报错部分
```linux
[DefaultDispatcher-worker-1] 03:11:15.699 INFO  VertExt - storage key: [data, ggtony, bookSource] path: /storage/data/ggtony/bookSource.json
[DefaultDispatcher-worker-1] 03:11:15.828 ERROR YueduApi - onHandlerError: 
io.vertx.core.json.DecodeException: Failed to decode: Unexpected end-of-input in field name
 at [Source: (StringReader); line: 73971, column: 26] (through reference chain: java.util.ArrayList[1588])
	at io.vertx.core.json.Json.decodeValue(Json.java:124)
	at io.vertx.core.json.JsonArray.fromJson(JsonArray.java:660)
	at io.vertx.core.json.JsonArray.<init>(JsonArray.java:53)
	at com.htmake.reader.utils.VertExtKt.asJsonArray(VertExt.kt:176)
	at com.htmake.reader.api.controller.BookController.loadBookSourceStringList(BookController.kt:1602)
	at com.htmake.reader.api.controller.BookController.loadBookSourceStringList$default(BookController.kt:1601)
	at com.htmake.reader.api.controller.BookController.getBookSourceBySourceURL(BookController.kt:1633)
	at com.htmake.reader.api.controller.BookController.getBookSourceStringBySourceURL(BookController.kt:1622)
	at com.htmake.reader.api.controller.BookController.getBookSourceStringBySourceURL$default(BookController.kt:1621)
	at com.htmake.reader.api.controller.BookController.getBookSourceString(BookController.kt:1596)
	at com.htmake.reader.api.controller.BookController.getChapterList(BookController.kt:351)
	at com.htmake.reader.api.YueduApi$initRouter$29.invokeSuspend(YueduApi.kt:181)
	at com.htmake.reader.api.YueduApi$initRouter$29.invoke(YueduApi.kt)
	at com.htmake.reader.api.YueduApi$initRouter$29.invoke(YueduApi.kt)
	at com.htmake.reader.verticle.RestVerticle$coroutineHandler$1$job$1.invokeSuspend(RestVerticle.kt:135)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
[DefaultDispatcher-worker-1] 03:11:15.828 INFO  LoggerHandlerImpl - 192.168.233.19 - - [Fri, 20 May 2022 19:11:15 GMT] "GET /reader3/getChapterList?url=https:%2F%2Fwww.yb3.cc%2F5200%2F25072%2F&refresh=0&accessToken=ggtony:b0ffcf63a81224dd85ba3325276f06b0 HTTP/1.1" 200 232 "http://192.168.233.110:39001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0"
```

**Comment by hectorqin** [comment]
json书源文件有问题

**Comment by ggtony233** [comment]
这是指我的书源有问题还是说这个镜像json书源的导入有问题？

**Comment by hectorqin** [comment]
书源
