### ISSUE TITLE
大文件本地书源导入报错

### ISSUE THREAD

**Issue by ZhangJiaLei123** [hectorqin/reader#136]
本地书源大概9M， 从app分享出来的，导入到web页面成功了，但是点击保存就报错了，如下：
```log
2022-06-11 16:17:03 [DefaultDispatcher-worker-13] ERROR com.htmake.reader.api.YueduApi - onHandlerError:
java.lang.IllegalArgumentException: Cannot construct instance of `io.legado.app.data.entities.BookSource`, problem: Should never call `set()` on setterless property ('headerMap')
 at [Source: UNKNOWN; line: -1, column: -1]
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3750)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3668)
        at io.vertx.core.json.JsonObject.mapTo(JsonObject.java:121)
        at com.htmake.reader.api.controller.BookSourceController.saveSources(BookSourceController.kt:155)
        at com.htmake.reader.api.YueduApi$initRouter$5.invokeSuspend(YueduApi.kt:138)
        at com.htmake.reader.api.YueduApi$initRouter$5.invoke(YueduApi.kt)
        at com.htmake.reader.api.YueduApi$initRouter$5.invoke(YueduApi.kt)
        at com.htmake.reader.verticle.RestVerticle$coroutineHandler$1$job$1.invokeSuspend(RestVerticle.kt:133)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.legado.app.data.entities.BookSource`, problem: Should never call `set()` on setterless property ('headerMap')
 at [Source: UNKNOWN; line: -1, column: -1]
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1608)
        at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1073)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapInstantiationProblem(BeanDeserializerBase.java:1754)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:490)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3745)
        ... 12 common frames omitted
Caused by: java.lang.UnsupportedOperationException: Should never call `set()` on setterless property ('headerMap')
        at com.fasterxml.jackson.databind.deser.impl.SetterlessProperty.set(SetterlessProperty.java:148)
        at com.fasterxml.jackson.databind.deser.impl.PropertyValue$Regular.assign(PropertyValue.java:62)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:204)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:488)
        ... 16 common frames omitted
```

**Comment by hectorqin** [comment]
是 docker的最新版本吗？
