### ISSUE TITLE
bug:导出EPUB功能无法正常使用

### ISSUE THREAD

**Issue by Tenkodo** [hectorqin/reader#161]
首先谢谢作者的辛苦开发 导出txt功能可以正常使用了，方便转换epub推送kindle了（当前kindle邮件支持推送epub了，同时kindle网页版太垃圾了所以要下载了看）

希望可以修复下书籍管理-导出epub功能（txt功能正常），目前导出时链接没反应，一直是载入状态，链接为导出txt的链接后面epub=1
![image](https://user-images.githubusercontent.com/62917736/177044851-c90e8719-9e27-4c9a-b64e-a020e35ed00e.png)

**Comment by hectorqin** [comment]
多等一会儿吧，可能章节太多，内容太大，生成比较慢

**Comment by Tenkodo** [comment]
> 多等一会儿吧，可能章节太多，内容太大，生成比较慢

载入久了直接504了……😢
![image](https://user-images.githubusercontent.com/62917736/177182179-885ddd08-f45f-4f71-a790-a39c66fb0d0a.png)

**Comment by hectorqin** [comment]
nginx的反向代理超时时间设长一点吧

**Comment by Tenkodo** [comment]
> nginx的反向代理超时时间设长一点吧

试了下用ip直接连接 半小时了还在转圈圈载入中😲

**Comment by hectorqin** [comment]
提供一下日志看看，你导出的有多少章节？

**Comment by core2duoe6420** [comment]
我通过Docker运行的reader，查看日志的时候显示这个错误：

```
Exception in thread "DefaultDispatcher-worker-8" java.lang.UnsupportedClassVersionError: org/xmlpull/v1/XmlPullParserFactory has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at me.ag2s.epublib.epub.EpubProcessorSupport.createXmlSerializer(EpubProcessorSupport.java:89)
	at me.ag2s.epublib.epub.EpubProcessorSupport.createXmlSerializer(EpubProcessorSupport.java:78)
	at me.ag2s.epublib.epub.NCXDocumentV2.createNCXResource(NCXDocumentV2.java:228)
	at me.ag2s.epublib.epub.NCXDocumentV2.createNCXResource(NCXDocumentV2.java:219)
	at me.ag2s.epublib.epub.EpubWriter.initTOCResource(EpubWriter.java:67)
	at me.ag2s.epublib.epub.EpubWriter.write(EpubWriter.java:48)
	at com.htmake.reader.api.controller.BookController.exportToEpub(BookController.kt:2820)
	at com.htmake.reader.api.controller.BookController.exportBook(BookController.kt:2708)
	at com.htmake.reader.api.YueduApi$initRouter$67.invokeSuspend(YueduApi.kt:257)
	at com.htmake.reader.api.YueduApi$initRouter$67.invoke(YueduApi.kt)
	at com.htmake.reader.api.YueduApi$initRouter$67.invoke(YueduApi.kt)
	at com.htmake.reader.verticle.RestVerticle$coroutineHandlerWithoutRes$1$job$1.invokeSuspend(RestVerticle.kt:149)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by hectorqin** [comment]
新版应该修复了
