### ISSUE TITLE
[BUG回报] 自2.5.5之后使用容器部署无法加载epub

### ISSUE THREAD

**Issue by Becods** [hectorqin/reader#203]
## 故障描述

自2.5.5之后使用容器部署无法加载epub

其中

2.5.5 提示`本地书籍源文件不存在`

2.5.6-2.5.7 请求拼接错误，域名与assets中间缺少`/`分隔

2.5.8 提示`本地书籍源文件不存在`

## 工作区快照

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/54435f56-9413-4e46-ba2c-cc451a78f6e0)

快照较大，打开需要较长时间，之后在终端输入`docker images`或`docker-compose up -d`激活即可，已加载测试用pdf

测试相关位于test目录中

## 日志

2.5.5和2.5.8的关键日志（似乎又回到了起点）
```
java.io.FileNotFoundException: /storageassetsdefaultbookFundamental-Accessibility-Tests-Basic-Functionalit.epub/index.epub (No such file or directory)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:228)
        at java.util.zip.ZipFile.<init>(ZipFile.java:157)
        at java.util.zip.ZipFile.<init>(ZipFile.java:171)
        at io.legado.app.model.localBook.EpubFile.readEpub(EpubFile.kt:142)
        at io.legado.app.model.localBook.EpubFile.getEpubBook(EpubFile.kt:107)
        at io.legado.app.model.localBook.EpubFile.getChapterListBySpine(EpubFile.kt:264)
        at io.legado.app.model.localBook.EpubFile.getChapterListBySpinAndToc(EpubFile.kt:331)
        at io.legado.app.model.localBook.EpubFile.getChapterListBySpinAndToc$default(EpubFile.kt:328)
        at io.legado.app.model.localBook.EpubFile$Companion.getChapterList(EpubFile.kt:62)
        at io.legado.app.model.localBook.LocalBook.getChapterList(LocalBook.kt:40)
        at com.htmake.reader.api.controller.BookController.importBookPreview(BookController.kt:265)
        at com.htmake.reader.api.YueduApi$initRouter$50.invokeSuspend(YueduApi.kt:237)
        at com.htmake.reader.api.YueduApi$initRouter$50.invoke(YueduApi.kt)
        at com.htmake.reader.api.YueduApi$initRouter$50.invoke(YueduApi.kt)
        at com.htmake.reader.verticle.RestVerticle$coroutineHandler$1$job$1.invokeSuspend(RestVerticle.kt:136)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

2.5.6和2.5.7的关键日志
```
me.ag2s.epublib.epub.NCXDocumentV3 me.ag2s.epublib.domain.TableOfContents@7277cca
java.lang.NullPointerException
        at io.legado.app.model.localBook.EpubFile.updateCover(EpubFile.kt:258)
        at io.legado.app.model.localBook.EpubFile.upBookInfo(EpubFile.kt:248)
        at io.legado.app.model.localBook.EpubFile.access$upBookInfo(EpubFile.kt:24)
        at io.legado.app.model.localBook.EpubFile$Companion.upBookInfo(EpubFile.kt:97)
        at io.legado.app.data.entities.Book.updateFromLocal(Book.kt:249)
        at io.legado.app.data.entities.Book.updateFromLocal$default(Book.kt:246)
        at io.legado.app.data.entities.Book$Companion.initLocalBook(Book.kt:286)
        at com.htmake.reader.api.controller.BookController.importBookPreview(BookController.kt:262)
        at com.htmake.reader.api.YueduApi$initRouter$50.invokeSuspend(YueduApi.kt:237)
        at com.htmake.reader.api.YueduApi$initRouter$50.invoke(YueduApi.kt)
        at com.htmake.reader.api.YueduApi$initRouter$50.invoke(YueduApi.kt)
        at com.htmake.reader.verticle.RestVerticle$coroutineHandler$1$job$1.invokeSuspend(RestVerticle.kt:136)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

剩下的日志和编译脚本，我放到[gist](https://gist.github.com/Becods/0261b3d1bb19fccb7addb1edc0ae7abe)了

## 可能的解决方法

docker使用2.5.4或更低版本，暂时不要升级

**Comment by Becods** [comment]
> 试试 hectorqin/reader-pro 这个镜像看看

测试正常，能正常加载并阅览epub，无报错
