### ISSUE TITLE
docker报错 TypeError: Cannot read property "length" from null

### ISSUE THREAD

**Issue by qinfengge** [hectorqin/reader#234]
搭好后添加书源，搜索，webdav一切都OK，吃灰了几天今天心血来潮看了一下
`2022-09-25T08:20:00.744234191Z Caused by: org.mozilla.javascript.WrappedException: Wrapped com.script.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from null (<Unknown source>#6) in <Unknown source> at line number 6 (<Unknown source>#1)
2022-09-25T08:20:00.744241502Z  at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1905)
2022-09-25T08:20:00.744245518Z  at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
2022-09-25T08:20:00.744249528Z  at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
2022-09-25T08:20:00.744268163Z  at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
2022-09-25T08:20:00.744272515Z  at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
2022-09-25T08:20:00.744276657Z  at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
2022-09-25T08:20:00.744286564Z  at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
2022-09-25T08:20:00.744290794Z  at com.script.javascript.RhinoScriptEngine$1.superDoTopCall(RhinoScriptEngine.java:92)
2022-09-25T08:20:00.744295021Z  at com.script.javascript.RhinoScriptEngine$1.doTopCall(RhinoScriptEngine.java:85)
2022-09-25T08:20:00.744299162Z  at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3651)
2022-09-25T08:20:00.744303288Z  at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:121)
2022-09-25T08:20:00.744307565Z  at org.mozilla.javascript.Context.evaluateReader(Context.java:1265)
2022-09-25T08:20:00.744311606Z  at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:161)
2022-09-25T08:20:00.744315839Z  ... 20 more
2022-09-25T08:20:00.744493840Z Caused by: com.script.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from null (<Unknown source>#6) in <Unknown source> at line number 6
2022-09-25T08:20:00.744501584Z  at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:171)
2022-09-25T08:20:00.744505828Z  at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:187)
2022-09-25T08:20:00.744509873Z  at com.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:79)
2022-09-25T08:20:00.744513947Z  at io.legado.app.model.analyzeRule.AnalyzeRule.evalJS(AnalyzeRule.kt:662)
2022-09-25T08:20:00.744518065Z  at io.legado.app.model.analyzeRule.AnalyzeRule.getElements(AnalyzeRule.kt:321)
2022-09-25T08:20:00.744613062Z  at io.legado.app.model.webBook.BookList.analyzeBookList(BookList.kt:66)
2022-09-25T08:20:00.744620014Z  at io.legado.app.model.webBook.WebBook.searchBook(WebBook.kt:72)
2022-09-25T08:20:00.744624166Z  at io.legado.app.model.webBook.WebBook$searchBook$1.invokeSuspend(WebBook.kt)
2022-09-25T08:20:00.744628346Z  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-09-25T08:20:00.744632365Z  at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
2022-09-25T08:20:00.744636050Z  at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
2022-09-25T08:20:00.744639840Z  at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:80)
2022-09-25T08:20:00.744724534Z  at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
2022-09-25T08:20:00.744731166Z  at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2022-09-25T08:20:00.744754123Z  at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
2022-09-25T08:20:00.744758957Z  at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2022-09-25T08:20:00.744762740Z  at io.legado.app.model.analyzeRule.AnalyzeRule.reGetBook(AnalyzeRule.kt:705)
2022-09-25T08:20:00.744766402Z  at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
2022-09-25T08:20:00.744777448Z  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-09-25T08:20:00.744781701Z  at java.lang.reflect.Method.invoke(Method.java:498)
2022-09-25T08:20:00.744785675Z  at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
2022-09-25T08:20:00.744789649Z  ... 31 more
2022-09-25T08:20:00.744798140Z Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from null (<Unknown source>#6)
2022-09-25T08:20:00.744802842Z  at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4354)
2022-09-25T08:20:00.744806968Z  at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4332)
2022-09-25T08:20:00.744810992Z  at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4365)
2022-09-25T08:20:00.744814979Z  at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4384)
2022-09-25T08:20:00.744832535Z  at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:4396)
2022-09-25T08:20:00.744837009Z  at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1589)
2022-09-25T08:20:00.744840923Z  at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1455)
2022-09-25T08:20:00.744844873Z  at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
2022-09-25T08:20:00.744848912Z  at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:124)
2022-09-25T08:20:00.744852970Z  at org.mozilla.javascript.Context.evaluateReader(Context.java:1265)
2022-09-25T08:20:00.744857134Z  at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:161)
2022-09-25T08:20:00.744861161Z  ... 51 more
2022-09-25T08:30:00.452881281Z javax.crypto.IllegalBlockSizeException: Input length must be multiple of 16 when decrypting with padded cipher
2022-09-25T08:30:00.453397587Z  at com.sun.crypto.provider.CipherCore.prepareInputBuffer(CipherCore.java:1005)
2022-09-25T08:30:00.453537597Z  at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:848)
2022-09-25T08:30:00.453670081Z  at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
2022-09-25T08:30:00.453789286Z  at javax.crypto.Cipher.doFinal(Cipher.java:2164)
2022-09-25T08:30:00.453896695Z  at io.legado.app.utils.EncoderUtils.symmetricTemplate(EncoderUtils.kt:164)
2022-09-25T08:30:00.454027040Z  at io.legado.app.utils.EncoderUtils.decryptAES(EncoderUtils.kt:126)
2022-09-25T08:30:00.454158433Z  at io.legado.app.utils.EncoderUtils.decryptBase64AES(EncoderUtils.kt:105)
2022-09-25T08:30:00.454285736Z  at io.legado.app.help.JsExtensions$DefaultImpls.aesBase64DecodeToByteArray(JsExtensions.kt:633)
2022-09-25T08:30:00.456098093Z  at io.legado.app.model.analyzeRule.AnalyzeRule.aesBase64DecodeToByteArray(AnalyzeRule.kt:32)
2022-09-25T08:30:00.456227962Z  at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
2022-09-25T08:30:00.456383368Z  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-09-25T08:30:00.456440929Z  at java.lang.reflect.Method.invoke(Method.java:498)
2022-09-25T08:30:00.456449727Z  at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
2022-09-25T08:30:00.456481862Z  at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
2022-09-25T08:30:00.456640333Z  at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
2022-09-25T08:30:00.456648493Z  at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
2022-09-25T08:30:00.456652857Z  at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:124)
2022-09-25T08:30:00.456656468Z  at org.mozilla.javascript.Context.evaluateReader(Context.java:1265)
2022-09-25T08:30:00.456659141Z  at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:161)
2022-09-25T08:30:00.456661811Z  at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:187)
2022-09-25T08:30:00.456664436Z  at com.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:79)
2022-09-25T08:30:00.456667126Z  at io.legado.app.model.analyzeRule.AnalyzeRule.evalJS(AnalyzeRule.kt:662)
2022-09-25T08:30:00.456969048Z  at io.legado.app.model.analyzeRule.AnalyzeRule.getElements(AnalyzeRule.kt:321)
2022-09-25T08:30:00.456978926Z  at io.legado.app.model.webBook.BookList.analyzeBookList(BookList.kt:66)
2022-09-25T08:30:00.456982663Z  at io.legado.app.model.webBook.WebBook.searchBook(WebBook.kt:72)
2022-09-25T08:30:00.456986395Z  at io.legado.app.model.webBook.WebBook$searchBook$1.invokeSuspend(WebBook.kt)
2022-09-25T08:30:00.456990000Z  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-09-25T08:30:00.456993765Z  at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
2022-09-25T08:30:00.456997736Z  at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
2022-09-25T08:30:00.457010503Z  at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:80)
2022-09-25T08:30:00.457014366Z  at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
2022-09-25T08:30:00.457018324Z  at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
2022-09-25T08:30:00.457021966Z  at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
2022-09-25T08:30:00.457026164Z  at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
2022-09-25T08:30:00.457030168Z  at io.legado.app.model.analyzeRule.AnalyzeRule.reGetBook(AnalyzeRule.kt:705)
2022-09-25T08:30:00.457033775Z  at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
2022-09-25T08:30:00.457037399Z  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-09-25T08:30:00.457051842Z  at java.lang.reflect.Method.invoke(Method.java:498)
2022-09-25T08:30:00.457055616Z  at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
2022-09-25T08:30:00.457059539Z  at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
2022-09-25T08:30:00.457063095Z  at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
2022-09-25T08:30:00.457066787Z  at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
2022-09-25T08:30:00.457070230Z  at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
2022-09-25T08:30:00.457073884Z  at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
2022-09-25T08:30:00.457077420Z  at com.script.javascript.RhinoScriptEngine$1.superDoTopCall(RhinoScriptEngine.java:92)
2022-09-25T08:30:00.457080963Z  at com.script.javascript.RhinoScriptEngine$1.doTopCall(RhinoScriptEngine.java:85)
2022-09-25T08:30:00.457084475Z  at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3651)
2022-09-25T08:30:00.457087898Z  at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:121)
2022-09-25T08:30:00.457091568Z  at org.mozilla.javascript.Context.evaluateReader(Context.java:1265)
2022-09-25T08:30:00.457094995Z  at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:161)
2022-09-25T08:30:00.457099353Z  at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:187)
2022-09-25T08:30:00.457103602Z  at com.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:79)
2022-09-25T08:30:00.457107796Z  at io.legado.app.model.analyzeRule.AnalyzeRule.evalJS(AnalyzeRule.kt:662)
2022-09-25T08:30:00.457112013Z  at io.legado.app.model.analyzeRule.AnalyzeRule.evalJS$default(AnalyzeRule.kt:649)
2022-09-25T08:30:00.457115616Z  at com.htmake.reader.api.controller.BookController.getLocalChapterList(BookController.kt:1881)
2022-09-25T08:30:00.457119243Z  at com.htmake.reader.api.controller.BookController$getBookShelfBooks$2$1.invokeSuspend(BookController.kt:1827)
2022-09-25T08:30:00.457123042Z  at com.htmake.reader.api.controller.BookController$getBookShelfBooks$2$1.invoke(BookController.kt)
2022-09-25T08:30:00.457126785Z  at com.htmake.reader.api.controller.BookController$getBookShelfBooks$2$1.invoke(BookController.kt)
2022-09-25T08:30:00.457130436Z  at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
2022-09-25T08:30:00.457133978Z  at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:155)
2022-09-25T08:30:00.457137689Z  at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
2022-09-25T08:30:00.457141725Z  at com.htmake.reader.api.controller.BookController$getBookShelfBooks$2.invokeSuspend(BookController.kt:1825)
2022-09-25T08:30:00.457145985Z  at com.htmake.reader.api.controller.BookController$getBookShelfBooks$2.invoke(BookController.kt)
2022-09-25T08:30:00.457155371Z  at com.htmake.reader.api.controller.BookController$getBookShelfBooks$2.invoke(BookController.kt)
2022-09-25T08:30:00.457158855Z  at com.htmake.reader.api.controller.BaseController$limitConcurrent$4.invokeSuspend(BaseController.kt:328)
2022-09-25T08:30:00.457162302Z  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-09-25T08:30:00.457165990Z  at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
2022-09-25T08:30:00.457169583Z  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
2022-09-25T08:30:00.457173262Z  at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
2022-09-25T08:30:00.457176805Z  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)`
大部分都是这种报错，还有一部分websocket超时的问题，应该是后端歇逼了，前端通不了信

**Comment by qinfengge** [comment]
真是书源问题啊，用的推荐的书源，今天再打开它又好了，不报错了
![CatCatsGIF](https://user-images.githubusercontent.com/35164697/194680867-f23f66e7-8886-4bce-9cdf-e3c353b02184.gif)
