### ISSUE TITLE
获取章节目录失败！

### ISSUE THREAD

**Issue by yayaleslie** [hectorqin/reader#249]
大佬们，这个问题如何解决

![image](https://user-images.githubusercontent.com/19268555/196046694-89a113df-1478-4645-889a-6c2353f72494.png)

**Comment by yayaleslie** [comment]
> 提供一下接口日志

就是看小说那个界面，浏览器后台一段时间，就会报这个错误，然后必须退回首页刷新 重进才行

reader      | 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
reader      | 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:155)
reader      | 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
reader      | 	at com.htmake.reader.api.controller.BookController$getBookShelfBooks$2.invokeSuspend(BookController.kt:1825)
reader      | 	at com.htmake.reader.api.controller.BookController$getBookShelfBooks$2.invoke(BookController.kt)
reader      | 	at com.htmake.reader.api.controller.BookController$getBookShelfBooks$2.invoke(BookController.kt)
reader      | 	at com.htmake.reader.api.controller.BaseController$limitConcurrent$4.invokeSuspend(BaseController.kt:328)
reader      | 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
reader      | 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
reader      | 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
reader      | 	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
reader      | 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
reader      | Caused by: org.mozilla.javascript.WrappedException: Wrapped com.script.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from null (<Unknown source>#6) in <Unknown source> at line number 6 (<Unknown source>#1)
reader      | 	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1905)
reader      | 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
reader      | 	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
reader      | 	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
reader      | 	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
reader      | 	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
reader      | 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
reader      | 	at com.script.javascript.RhinoScriptEngine$1.superDoTopCall(RhinoScriptEngine.java:92)
reader      | 	at com.script.javascript.RhinoScriptEngine$1.doTopCall(RhinoScriptEngine.java:85)
reader      | 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3651)
reader      | 	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:121)
reader      | 	at org.mozilla.javascript.Context.evaluateReader(Context.java:1265)
reader      | 	at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:161)
reader      | 	... 20 more
reader      | Caused by: com.script.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from null (<Unknown source>#6) in <Unknown source> at line number 6
reader      | 	at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:171)
reader      | 	at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:187)
reader      | 	at com.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:79)
reader      | 	at io.legado.app.model.analyzeRule.AnalyzeRule.evalJS(AnalyzeRule.kt:662)
reader      | 	at io.legado.app.model.analyzeRule.AnalyzeRule.getElements(AnalyzeRule.kt:321)
reader      | 	at io.legado.app.model.webBook.BookList.analyzeBookList(BookList.kt:66)
reader      | 	at io.legado.app.model.webBook.WebBook.searchBook(WebBook.kt:72)
reader      | 	at io.legado.app.model.webBook.WebBook$searchBook$1.invokeSuspend(WebBook.kt)
reader      | 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
reader      | 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
reader      | 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
reader      | 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:80)
reader      | 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
reader      | 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
reader      | 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
reader      | 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
reader      | 	at io.legado.app.model.analyzeRule.AnalyzeRule.reGetBook(AnalyzeRule.kt:705)
reader      | 	at sun.reflect.GeneratedMethodAccessor61.invoke(Unknown Source)
reader      | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
reader      | 	at java.lang.reflect.Method.invoke(Method.java:498)
reader      | 	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
reader      | 	... 31 more
reader      | Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from null (<Unknown source>#6)
reader      | 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4354)
reader      | 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4332)
reader      | 	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4365)
reader      | 	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:4384)
reader      | 	at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:4396)
reader      | 	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1589)
reader      | 	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1455)
reader      | 	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
reader      | 	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:124)
reader      | 	at org.mozilla.javascript.Context.evaluateReader(Context.java:1265)
reader      | 	at com.script.javascript.RhinoScriptEngine.eval(RhinoScriptEngine.java:161)
reader      | 	... 51 more
reader      | java.net.SocketTimeoutException: timeout
reader      | 	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
reader      | 	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
reader      | 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:335)
reader      | 	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
reader      | 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
reader      | 	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
reader      | 	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
reader      | 	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
reader      | 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
reader      | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
reader      | 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
reader      | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
reader      | 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
reader      | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
reader      | 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
reader      | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
reader      | 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
reader      | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
reader      | 	at io.legado.app.help.http.HttpHelperKt$okHttpClient$2.invoke$lambda-0(HttpHelper.kt:50)
reader      | 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
reader      | 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
reader      | 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
reader      | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
reader      | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
reader      | 	at java.lang.Thread.run(Thread.java:748)
reader      | Caused by: java.net.SocketException: Socket closed
reader      | 	at java.net.SocketInputStream.read(SocketInputStream.java:204)
reader      | 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
reader      | 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
reader      | 	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
reader      | 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
reader      | 	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
reader      | 	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
reader      | 	at okio.InputStreamSource.read(JvmOkio.kt:90)
reader      | 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
reader      | 	... 22 more
