### ISSUE TITLE
想请教一下，replit.com上怎么部署

### ISSUE THREAD

**Issue by synge0718** [hectorqin/reader#266]
RT，之前用Railway部署的，但是现在有每月500h的限制，想换一个平台，看到replit.com也可以部署，并且没有限制时间，但是部署了提示失败，不知道是不是要修改什么地方
 java -jar main.jar
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
    at MainKt.main(main.kt)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    ... 1 more
exit status 1

**Comment by synge0718** [comment]
> 

我是直接在replit.com里导入我fork的项目的，但是run的时候提示要Configure the Run Command，不知道该怎么运行

**Comment by synge0718** [comment]
> 你怎么部署的？运行命令有问题

默认是这个运行命令：kotlinc -d main.jar
![image](https://user-images.githubusercontent.com/31887102/199684310-440cedca-cb40-4a2e-919e-347d2265e3ce.png)

**Comment by andbruibm** [comment]
![image](https://user-images.githubusercontent.com/106566161/200117804-782a2631-436d-4950-8d2d-d83a034ccbe1.png)
用这个运行java -jar XXX.jar就可以了

**Comment by andbruibm** [comment]
> > 
> 
> 我是直接在replit.com里导入我fork的项目的，但是run的时候提示要Configure the Run Command，不知道该怎么运行

你可以直接fork我弄好的https://replit.com/@andbru123/reader?v=1

**Comment by synge0718** [comment]
> 

我已经fork了，可以用，非常感谢；就是到时候如果作者更新了，这个仓库怎么更新呢

**Comment by synge0718** [comment]
> > > 
> > 
> > 
> > 我是直接在replit.com里导入我fork的项目的，但是run的时候提示要Configure the Run Command，不知道该怎么运行
> 
> 你可以直接fork我弄好的https://replit.com/@andbru123/reader?v=1

我已经fork了，可以用，非常感谢；就是到时候如果作者更新了，这个仓库怎么更新呢
