### ISSUE TITLE
docker 安装的 reader页 F5 刷新报错

### ISSUE THREAD

**Issue by kongxiangyiren** [hectorqin/reader#277]
![image](https://user-images.githubusercontent.com/72970235/203905605-e344ad88-fcef-4a0f-ad8b-988a38269402.png)

[DefaultDispatcher-worker-2] 13:07:57.134 INFO  VertExt - Read file from storage name: [data, admin, 神级售货商_风雨神话, 2c817e10d566eeaa8e285bf7760f53ee] path: /storage/data/admin/神级售货商_风雨神话/2c817e10d566eeaa8e285bf7760f53ee.json
[DefaultDispatcher-worker-2] 13:07:57.178 INFO  VertExt - Read file from storage name: [data, admin, bookshelf] path: /storage/data/admin/bookshelf.json
[DefaultDispatcher-worker-2] 13:07:57.190 INFO  VertExt - Save file to storage name: [data, admin, bookshelf] path: /storage/data/admin/bookshelf.json
[DefaultDispatcher-worker-2] 13:07:57.219 INFO  WebBook - bookChapterUrl: /so/83046/30671195.html
[DefaultDispatcher-worker-5] 13:07:57.427 INFO  LoggerHandlerImpl - 172.18.0.1 - - [Fri, 25 Nov 2022 05:07:56 GMT] "POST /reader3/getBookContent?accessToken=admin:ed75256d74c0e733f8210253d7044cac&v=1669352876039 HTTP/1.1" 200 9225 "http://127.0.0.1:4396/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
[vert.x-eventloop-thread-0] 13:07:59.653 INFO  LoggerHandlerImpl - 172.18.0.1 - - [Fri, 25 Nov 2022 05:07:59 GMT] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
[vert.x-eventloop-thread-0] 13:07:59.810 INFO  RestVerticle - GET http://127.0.0.1:4396/reader3/getUserInfo?accessToken=admin:ed75256d74c0e733f8210253d7044cac&v=1669352879802
[DefaultDispatcher-worker-23] 13:07:59.810 INFO  VertExt - Read file from storage name: [data, users] path: /storage/data/users.json
[DefaultDispatcher-worker-23] 13:07:59.816 INFO  VertExt - Read file from storage name: [data, users] path: /storage/data/users.json
[DefaultDispatcher-worker-23] 13:07:59.822 INFO  LoggerHandlerImpl - 172.18.0.1 - - [Fri, 25 Nov 2022 05:07:59 GMT] "GET /reader3/getUserInfo?accessToken=admin:ed75256d74c0e733f8210253d7044cac&v=1669352879802 HTTP/1.1" 200 259 "http://127.0.0.1:4396/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
[vert.x-eventloop-thread-0] 13:07:59.843 INFO  RestVerticle - POST http://127.0.0.1:4396/reader3/getChapterList?accessToken=admin:ed75256d74c0e733f8210253d7044cac&v=1669352879823
[vert.x-eventloop-thread-0] 13:07:59.843 INFO  RestVerticle - Request body: {"refresh":0}
[vert.x-eventloop-thread-0] 13:07:59.844 INFO  RestVerticle - GET http://127.0.0.1:4396/reader3/getTxtTocRules?accessToken=admin:ed75256d74c0e733f8210253d7044cac&v=1669352879816
[DefaultDispatcher-worker-23] 13:07:59.844 INFO  VertExt - Read file from storage name: [data, users] path: /storage/data/users.json
[DefaultDispatcher-worker-11] 13:07:59.844 INFO  VertExt - Read file from storage name: [data, users] path: /storage/data/users.json
[DefaultDispatcher-worker-23] 13:07:59.851 ERROR YueduApi - onHandlerError: 
java.lang.NullPointerException: null
	at com.htmake.reader.api.controller.BookController.getChapterList(BookController.kt:370)
	at com.htmake.reader.api.YueduApi$initRouter$35.invokeSuspend(YueduApi.kt:221)
	at com.htmake.reader.api.YueduApi$initRouter$35.invoke(YueduApi.kt)
	at com.htmake.reader.api.YueduApi$initRouter$35.invoke(YueduApi.kt)
	at com.htmake.reader.verticle.RestVerticle$coroutineHandler$1$job$1.invokeSuspend(RestVerticle.kt:138)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
[DefaultDispatcher-worker-23] 13:07:59.851 INFO  LoggerHandlerImpl - 172.18.0.1 - - [Fri, 25 Nov 2022 05:07:59 GMT] "POST /reader3/getChapterList?accessToken=admin:ed75256d74c0e733f8210253d7044cac&v=1669352879823 HTTP/1.1" 200 63 "http://127.0.0.1:4396/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
[DefaultDispatcher-worker-11] 13:07:59.852 INFO  LoggerHandlerImpl - 172.18.0.1 - - [Fri, 25 Nov 2022 05:07:59 GMT] "GET /reader3/getTxtTocRules?accessToken=admin:ed75256d74c0e733f8210253d7044cac&v=1669352879816 HTTP/1.1" 200 4931 "http://127.0.0.1:4396/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
[vert.x-eventloop-thread-0] 13:07:59.902 INFO  RestVerticle - GET http://127.0.0.1:4396/reader3/getBookshelf?refresh=0&accessToken=admin:ed75256d74c0e733f8210253d7044cac&v=1669352879842
[DefaultDispatcher-worker-11] 13:07:59.902 INFO  VertExt - Read file from storage name: [data, users] path: /storage/data/users.json
[DefaultDispatcher-worker-11] 13:07:59.910 INFO  VertExt - Read file from storage name: [data, admin, bookshelf] path: /storage/data/admin/bookshelf.json
[DefaultDispatcher-worker-11] 13:07:59.919 INFO  VertExt - Read file from storage name: [data, admin, bookSource] path: /storage/data/admin/bookSource.json
[DefaultDispatcher-worker-6] 13:08:00.790 INFO  LoggerHandlerImpl - 172.18.0.1 - - [Fri, 25 Nov 2022 05:07:59 GMT] "GET /reader3/getBookshelf?refresh=0&accessToken=admin:ed75256d74c0e733f8210253d7044cac&v=1669352879842 HTTP/1.1" 200 5114 "http://127.0.0.1:4396/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
[vert.x-eventloop-thread-0] 13:08:00.814 INFO  RestVerticle - GET http://127.0.0.1:4396/reader3/getBookGroups?accessToken=admin:ed75256d74c0e733f8210253d7044cac&v=1669352880806
[DefaultDispatcher-worker-14] 13:08:00.815 INFO  VertExt - Read file from storage name: [data, users] path: /storage/data/users.json
[vert.x-eventloop-thread-0] 13:08:00.817 INFO  RestVerticle - GET http://127.0.0.1:4396/reader3/getRssSources?simple=1&accessToken=admin:ed75256d74c0e733f8210253d7044cac&v=1669352880809
[DefaultDispatcher-worker-11] 13:08:00.818 INFO  VertExt - Read file from storage name: [data, users] path: /storage/data/users.json

**Comment by kongxiangyiren** [comment]
刷新后 要在书架重新点击才行

**Comment by kongxiangyiren** [comment]
还是不行


[9f77094e] [DefaultDispatcher-worker-2] 15:46:01.334 ERROR YueduApi - onHandlerError: 
java.lang.NullPointerException: null
	at com.htmake.reader.api.controller.BookController.getChapterList(BookController.kt:379)
	at com.htmake.reader.api.YueduApi$initRouter$36.invokeSuspend(YueduApi.kt:248)
	at com.htmake.reader.api.YueduApi$initRouter$36.invoke(YueduApi.kt)
	at com.htmake.reader.api.YueduApi$initRouter$36.invoke(YueduApi.kt)
	at com.htmake.reader.verticle.RestVerticle$coroutineHandler$1$2.invokeSuspend(RestVerticle.kt:163)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[9f77094e] [DefaultDispatcher-worker-2] 15:46:01.335 INFO  LoggerHandlerImpl - 172.18.0.1 - - [Thu, 9 Mar 2023 07:46:01 GMT] 


![image](https://user-images.githubusercontent.com/72970235/223955135-f7dfe9de-9c74-4b9b-bb7f-363fd81300a0.png)


如果不刷新页面就没问题，一刷新就报错
