### ISSUE TITLE
无法搜索书籍

### ISSUE THREAD

**Issue by uni-pai** [hectorqin/reader#3]
后端部署完成，且导入书源后无法搜索书籍。已多次尝试并更换书源尝试后仍是显示无法连接后端。浏览器截图及后端数据如下：
![Snipaste_2021-09-02_20-26-59](https://user-images.githubusercontent.com/56943441/131843951-eb26c293-ccb8-406b-86f1-95219afd80c9.jpg)

` F:\Reader\storage\bookSource.json
2021-09-02 20:26:26 [DefaultDispatcher-worker-1] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 0:0:0:0:0:0:0:1 - - [Thu, 02 Sep 2021 12:26:26 GMT] "GET /reader3/getSources HTTP/1.1" 200 385759 "http://localhost:8080/web/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"
2021-09-02 20:26:45 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - request url: http://localhost:8080/reader3/searchBook?key=瀹岀編涓栫晫&bookSourceUrl=https://www.shukeba.com
2021-09-02 20:26:45 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - request body:
2021-09-02 20:26:45 [DefaultDispatcher-worker-1] INFO  org.lightink.reader.api.YueduApi - searchBook
Exception in thread "DefaultDispatcher-worker-1" java.lang.IllegalAccessError: class com.sun.script.javascript.RhinoScriptEngine (in unnamed module @0x7006c658) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x7006c658
        at com.sun.script.javascript.RhinoScriptEngine.getLanguageVersion(RhinoScriptEngine.java:154)
        at com.sun.script.javascript.RhinoScriptEngine.<clinit>(RhinoScriptEngine.java:97)
        at com.sun.script.javascript.RhinoScriptEngineFactory.getScriptEngine(RhinoScriptEngineFactory.java:78)
        at java.scripting/javax.script.ScriptEngineManager.getEngineByName(ScriptEngineManager.java:241)
        at io.legado.app.constant.AppConst$SCRIPT_ENGINE$2.invoke(AppConst.kt:17)
        at io.legado.app.constant.AppConst$SCRIPT_ENGINE$2.invoke(AppConst.kt:7)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.legado.app.constant.AppConst.getSCRIPT_ENGINE(AppConst.kt)
        at io.legado.app.model.analyzeRule.AnalyzeUrl.replaceKeyPageJs(AnalyzeUrl.kt:138)
        at io.legado.app.model.analyzeRule.AnalyzeUrl.<init>(AnalyzeUrl.kt:67)
        at io.legado.app.model.analyzeRule.AnalyzeUrl.<init>(AnalyzeUrl.kt:40)
        at io.legado.app.model.WebBook.searchBook(WebBook.kt:32)
        at org.lightink.reader.api.YueduApi.searchBook(YueduApi.kt:338)
        at org.lightink.reader.api.YueduApi$initRouter$13.invokeSuspend(YueduApi.kt:79)
        at org.lightink.reader.api.YueduApi$initRouter$13.invoke(YueduApi.kt)
        at org.lightink.reader.verticle.RestVerticle$coroutineHandler$1$job$1.invokeSuspend(RestVerticle.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)`

**Comment by hectorqin** [comment]
应该是源不兼容，可能对使用js的源不太支持，换个源应该就可以了

**Comment by uni-pai** [comment]
请问能提供一个源的例子吗？
我尝试了各种书源都是这样的问题。

**Comment by hectorqin** [comment]
https://github.com/safino9/SourceGo/blob/main/book_source/all.json

**Comment by uni-pai** [comment]
依旧是该问题。

**Comment by hectorqin** [comment]
这个源用了 javascript，目前不要使用 javascript 的源
