### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by RocheNotFound** [hectorqin/reader#306]
io.vertx.core.json.DecodeException: Failed to decode:No content to map due to end-of-input at [Source: (String)""; line: 1, column: 0]
用replit部署的，之前一直挺好的，今天后端可以连接但无法正常看书。试着刷新就会弹出这段代码。
接着用render又部署了一个，但又遇到了问题：无法正常搜索。往往搜索了一秒不到就会停止搜索。同样后端也是正常连接的。
由于我没有学过编程，所以我看不懂，想让大佬帮我解决一下qwq。
又及：是云服务器的问题吗？是否需要换一个云服务器？如果要换的话可以推荐一个吗？
（koyeb注册一直不给发邮件，RailwayGithub账号还没满足注册时间限制，又听说用Railway部署也会有问题，Heroku无法注册，点击注册后是白屏。）
请大佬指点！

**Comment by RocheNotFound** [comment]
emmm……还有一个问题就是当后端从未连接变为连接时会自动变成白天模式…(上个问题也还没解决

**Comment by Michaela-Jackson** [comment]
我也遇到同样的问题了！！求解

**Comment by SheepYY039** [comment]
> > emmm……还有一个问题就是当后端从未连接变为连接时会自动变成白天模式…(上个问题也还没解决
> 
> 看看是不是勾选了 自动切换 黑夜白天主题？

我也出现同样问题了，检查过 自动切换 黑夜白天主题，本来是勾选的，然后我再`userConfig.json`改为`false` 然后`docker-compose` 重新启动，但是问题还是出现

**Comment by RocheNotFound** [comment]
io.vertx.core.json.DecodeException: Failed to decode:No content to map due to end-of-input at [Source: (String)""; line: 1, column: 0]
这段代码又出现了……这是数据又丢失了？

**Comment by RocheNotFound** [comment]
2023-04-09 08:12:04 [14f938dc] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/reader3/getUserInfo?v=1681027925396
2023-04-09 08:12:04 [14f938dc] [DefaultDispatcher-worker-1] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 172.31.128.1 - - [Sun, 9 Apr 2023 08:12:04 GMT] "GET /reader3/getUserInfo?v=1681027925396 HTTP/1.1" 200 74 "https://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
2023-04-09 08:12:05 [9335196d] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/reader3/getBookshelf?refresh=0&v=1681027925829
2023-04-09 08:12:05 [9335196d] [DefaultDispatcher-worker-1] INFO  com.htmake.reader.utils.Ext - Read file from storage name: [data, default, bookshelf] path: /home/runner/reader/storage/data/default/bookshelf.json
2023-04-09 08:12:05 [9335196d] [DefaultDispatcher-worker-1] ERROR com.htmake.reader.utils.Ext - 解析内容出错: io.vertx.core.json.DecodeException: Failed to decode:No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]  内容: 

2023-04-09 08:12:05 [9335196d] [DefaultDispatcher-worker-1] ERROR com.htmake.reader.api.YueduApi - onHandlerError: 
io.vertx.core.json.DecodeException: Failed to decode:No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
    at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:97)
    at io.vertx.core.json.jackson.JacksonCodec.fromString(JacksonCodec.java:57)
    at io.vertx.core.json.JsonArray.fromJson(JsonArray.java:845)
    at io.vertx.core.json.JsonArray.<init>(JsonArray.java:54)
    at com.htmake.reader.utils.ExtKt.asJsonArray(Ext.kt:439)
    at com.htmake.reader.api.controller.BookController.getBookShelfBooks(BookController.kt:1892)
    at com.htmake.reader.api.controller.BookController.getBookshelf(BookController.kt:1279)
    at com.htmake.reader.api.YueduApi$initRouter$21.invokeSuspend(YueduApi.kt:233)
    at com.htmake.reader.api.YueduApi$initRouter$21.invoke(YueduApi.kt)
    at com.htmake.reader.api.YueduApi$initRouter$21.invoke(YueduApi.kt)
    at com.htmake.reader.verticle.RestVerticle$coroutineHandler$1$2.invokeSuspend(RestVerticle.kt:163)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
    at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
    at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3971)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
    at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:95)
    ... 16 common frames omitted
2023-04-09 08:12:05 [9335196d] [DefaultDispatcher-worker-1] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 172.31.128.1 - - [Sun, 9 Apr 2023 08:12:05 GMT] "GET /reader3/getBookshelf?refresh=0&v=1681027925829 HTTP/1.1" 200 171 "https://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
2023-04-09 08:12:05 [671a52ee] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/reader3/getBookshelf?refresh=0&v=1681027925927
2023-04-09 08:12:05 [671a52ee] [DefaultDispatcher-worker-1] INFO  com.htmake.reader.utils.Ext - Read file from storage name: [data, default, bookshelf] path: /home/runner/reader/storage/data/default/bookshelf.json
2023-04-09 08:12:05 [671a52ee] [DefaultDispatcher-worker-1] ERROR com.htmake.reader.utils.Ext - 解析内容出错: io.vertx.core.json.DecodeException: Failed to decode:No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]  内容: 

2023-04-09 08:12:05 [671a52ee] [DefaultDispatcher-worker-1] ERROR com.htmake.reader.api.YueduApi - onHandlerError: 
io.vertx.core.json.DecodeException: Failed to decode:No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
    at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:97)
    at io.vertx.core.json.jackson.JacksonCodec.fromString(JacksonCodec.java:57)
    at io.vertx.core.json.JsonArray.fromJson(JsonArray.java:845)
    at io.vertx.core.json.JsonArray.<init>(JsonArray.java:54)
    at com.htmake.reader.utils.ExtKt.asJsonArray(Ext.kt:439)
    at com.htmake.reader.api.controller.BookController.getBookShelfBooks(BookController.kt:1892)
    at com.htmake.reader.api.controller.BookController.getBookshelf(BookController.kt:1279)
    at com.htmake.reader.api.YueduApi$initRouter$21.invokeSuspend(YueduApi.kt:233)
    at com.htmake.reader.api.YueduApi$initRouter$21.invoke(YueduApi.kt)
    at com.htmake.reader.api.YueduApi$initRouter$21.invoke(YueduApi.kt)
    at com.htmake.reader.verticle.RestVerticle$coroutineHandler$1$2.invokeSuspend(RestVerticle.kt:163)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
    at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
    at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3971)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
    at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:95)
    ... 16 common frames omitted
2023-04-09 08:12:05 [671a52ee] [DefaultDispatcher-worker-1] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 172.31.128.1 - - [Sun, 9 Apr 2023 08:12:05 GMT] "GET /reader3/getBookshelf?refresh=0&v=1681027925927 HTTP/1.1" 200 171 "https://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
2023-04-09 08:12:05 [ac902b65] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/reader3/getTxtTocRules?v=1681027926117
2023-04-09 08:12:05 [ac902b65] [DefaultDispatcher-worker-1] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 172.31.128.1 - - [Sun, 9 Apr 2023 08:12:05 GMT] "GET /reader3/getTxtTocRules?v=1681027926117 HTTP/1.1" 200 4931 "https://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
2023-04-09 08:12:05 [831b1b29] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/reader3/getBookGroups?v=1681027926410
2023-04-09 08:12:05 [831b1b29] [DefaultDispatcher-worker-1] INFO  com.htmake.reader.utils.Ext - Read file from storage name: [data, default, bookGroup] path: /home/runner/reader/storage/data/default/bookGroup.json
2023-04-09 08:12:05 [831b1b29] [DefaultDispatcher-worker-1] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 172.31.128.1 - - [Sun, 9 Apr 2023 08:12:05 GMT] "GET /reader3/getBookGroups?v=1681027926410 HTTP/1.1" 200 346 "https://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
2023-04-09 08:12:05 [eed28b04] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/reader3/getRssSources?simple=1&v=1681027926543
2023-04-09 08:12:05 [eed28b04] [DefaultDispatcher-worker-2] INFO  com.htmake.reader.utils.Ext - Read file from storage name: [data, default, rssSources] path: /home/runner/reader/storage/data/default/rssSources.json
2023-04-09 08:12:05 [eed28b04] [DefaultDispatcher-worker-2] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 172.31.128.1 - - [Sun, 9 Apr 2023 08:12:05 GMT] "GET /reader3/getRssSources?simple=1&v=1681027926543 HTTP/1.1" 200 42 "https://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
2023-04-09 08:12:06 [b7e70772] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/reader3/getBookmarks?v=1681027926578
2023-04-09 08:12:06 [b7e70772] [DefaultDispatcher-worker-1] INFO  com.htmake.reader.utils.Ext - Read file from storage name: [data, default, bookmark] path: /home/runner/reader/storage/data/default/bookmark.json
2023-04-09 08:12:06 [b7e70772] [DefaultDispatcher-worker-1] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 172.31.128.1 - - [Sun, 9 Apr 2023 08:12:06 GMT] "GET /reader3/getBookmarks?v=1681027926578 HTTP/1.1" 200 42 "https://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
2023-04-09 08:12:06 [6f78ea44] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/reader3/getReplaceRules?v=1681027926560
2023-04-09 08:12:06 [6f78ea44] [DefaultDispatcher-worker-1] INFO  com.htmake.reader.utils.Ext - Read file from storage name: [data, default, replaceRule] path: /home/runner/reader/storage/data/default/replaceRule.json
2023-04-09 08:12:06 [6f78ea44] [DefaultDispatcher-worker-1] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 172.31.128.1 - - [Sun, 9 Apr 2023 08:12:06 GMT] "GET /reader3/getReplaceRules?v=1681027926560 HTTP/1.1" 200 42 "https://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
2023-04-09 08:12:06 [5484ec0a] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/reader3/getBookSources?simple=1&v=1681027926670
2023-04-09 08:12:06 [5484ec0a] [DefaultDispatcher-worker-2] INFO  com.htmake.reader.utils.Ext - Read file from storage name: [data, default, bookSource] path: /home/runner/reader/storage/data/default/bookSource.json
2023-04-09 08:12:06 [5484ec0a] [DefaultDispatcher-worker-2] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 172.31.128.1 - - [Sun, 9 Apr 2023 08:12:06 GMT] "GET /reader3/getBookSources?simple=1&v=1681027926670 HTTP/1.1" 200 717028 "https://c8b32305-b218-4a6a-8b1b-d4841728ac28.id.repl.co/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"
2023-04-09 08:12:09 [5484ec0a] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - 客户端已断开链接，终止运行
