### ISSUE TITLE
上传txt书籍文件报错 " onHandlerError: java.lang.IllegalStateException “

### ISSUE THREAD

**Issue by katyurua** [hectorqin/reader#31]
```
F:\reader3>java -jar reader-1.9.0.jar
██████  ███████  █████  ██████  ███████ ██████ 
██   ██ ██      ██   ██ ██   ██ ██      ██   ██ 
██████  █████   ███████ ██   ██ █████   ██████  
██   ██ ██      ██   ██ ██   ██ ██      ██   ██ 
██   ██ ███████ ██   ██ ██████  ███████ ██   ██ 
                                                

2022-04-16 13:14:02 [main] INFO  o.l.reader.ReaderApplicationKt - Starting ReaderApplicationKt on DESKTOP-1234with PID 11014 (F:\reader3\reader-1.9.0.jar started by admin in F:\reader3)
2022-04-16 13:14:02 [main] DEBUG o.l.reader.ReaderApplicationKt - Running with Spring Boot v2.1.6.RELEASE, Spring v5.1.8.RELEASE
2022-04-16 13:14:02 [main] INFO  o.l.reader.ReaderApplicationKt - No active profile set, falling back to default profiles: default
2022-04-16 13:14:03 [vert.x-eventloop-thread-2] INFO  org.lightink.reader.api.YueduApi - port: 8080
2022-04-16 13:14:03 [vert.x-eventloop-thread-2] INFO  org.lightink.reader.api.YueduApi - serverPort: 8080
2022-04-16 13:14:03 [vert.x-eventloop-thread-2] INFO  org.lightink.reader.utils.VertExt - osName: Windows 10 currentDir: F:\reader3
2022-04-16 13:14:03 [vert.x-eventloop-thread-2] INFO  org.lightink.reader.utils.VertExt - storage key: [cache, bookInfoCache] path: F:\storage\cache\bookInfoCache.json
2022-04-16 13:14:03 [vert.x-eventloop-thread-2] INFO  org.lightink.reader.utils.VertExt - storage key: [cache, invalidBookSourceList] path: F:\storage\cache\invalidBookSourceList.json
2022-04-16 13:14:03 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - port: 8080
2022-04-16 13:14:03 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService 'taskScheduler'
2022-04-16 13:14:03 [main] INFO  o.l.reader.ReaderApplicationKt - Started ReaderApplicationKt in 2.415 seconds (JVM running for 2.903)
2022-04-16 13:14:04 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - Server running at: http://localhost:8080
2022-04-16 13:14:04 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - Web reader running at: http://localhost:8080
2022-04-16 13:14:24 [vert.x-eventloop-thread-2] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 0:0:0:0:0:0:0:1 - - [Sat, 16 Apr 2022 05:14:24 GMT] "GET / HTTP/1.1" 200 4647 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"
2022-04-16 13:14:24 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - GET http://localhost:8080/reader3/getUserInfo
2022-04-16 13:14:24 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - request body:
2022-04-16 13:14:24 [DefaultDispatcher-worker-1] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 0:0:0:0:0:0:0:1 - - [Sat, 16 Apr 2022 05:14:24 GMT] "GET /reader3/getUserInfo HTTP/1.1" 200 74 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"
2022-04-16 13:14:24 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - GET http://localhost:8080/reader3/getBookshelf?refresh=0
2022-04-16 13:14:24 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - request body:
2022-04-16 13:14:24 [DefaultDispatcher-worker-1] INFO  org.lightink.reader.utils.VertExt - storage key: [data, default, bookshelf] path: F:\storage\data\default\bookshelf.json
2022-04-16 13:14:24 [DefaultDispatcher-worker-1] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 0:0:0:0:0:0:0:1 - - [Sat, 16 Apr 2022 05:14:24 GMT] "GET /reader3/getBookshelf?refresh=0 HTTP/1.1" 200 42 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"
2022-04-16 13:14:27 [vert.x-eventloop-thread-2] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 0:0:0:0:0:0:0:1 - - [Sat, 16 Apr 2022 05:14:27 GMT] "GET /service-worker.js HTTP/1.1" 200 5875 "http://localhost:8080/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"
2022-04-16 13:14:39 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - POST http://localhost:8080/reader3/importBookPreview
2022-04-16 13:14:39 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - request body:
2022-04-16 13:14:39 [DefaultDispatcher-worker-3] INFO  org.lightink.reader.api.YueduApi - uploadFile: file-uploads\a69c7f00-7223-4cba-a1ab-942a7f23c204 test.txt file-uploads\a69c7f00-7223-4cba-a1ab-942a7f23c204
2022-04-16 13:14:39 [DefaultDispatcher-worker-3] INFO  org.lightink.reader.api.YueduApi - moveTo: storage\assets\default\book\test.txt
2022-04-16 13:14:40 [DefaultDispatcher-worker-3] ERROR org.lightink.reader.api.YueduApi - onHandlerError:
java.lang.IllegalStateException: DefaultData::class.java.…tor}$txtTocRuleFileName") must not be null
        at io.legado.app.help.DefaultData$txtTocRules$2.invoke(DefaultData.kt:13)
        at io.legado.app.help.DefaultData$txtTocRules$2.invoke(DefaultData.kt:9)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.legado.app.help.DefaultData.getTxtTocRules(DefaultData.kt)
        at io.legado.app.localBook.TextFile$Companion.getTocRules(TextFile.kt:263)
        at io.legado.app.localBook.TextFile$Companion.access$getTocRules(TextFile.kt:240)
        at io.legado.app.localBook.TextFile.analyze(TextFile.kt:30)
        at io.legado.app.localBook.LocalBook.getChapterList(LocalBook.kt:26)
        at org.lightink.reader.api.YueduApi.importBookPreview(YueduApi.kt:1592)
        at org.lightink.reader.api.YueduApi$initRouter$55.invokeSuspend(YueduApi.kt:237)
        at org.lightink.reader.api.YueduApi$initRouter$55.invoke(YueduApi.kt)
        at org.lightink.reader.verticle.RestVerticle$coroutineHandler$1$job$1.invokeSuspend(RestVerticle.kt:133)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
2022-04-16 13:14:40 [DefaultDispatcher-worker-3] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 0:0:0:0:0:0:0:1 - - [Sat, 16 Apr 2022 05:14:39 GMT] "POST /reader3/importBookPreview HTTP/1.1" 200 136 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"

```

**Comment by hectorqin** [comment]
java版本多少？

**Comment by katyurua** [comment]
> java版本多少？

JDK 18

build 18+36-2087

**Comment by hectorqin** [comment]
试试低版本看看，好像是没读到resource

**Comment by katyurua** [comment]
> 试试低版本看看，好像是没读到resource

换到17了，还是报错

```
2022-04-16 16:58:49 [DefaultDispatcher-worker-2] ERROR org.lightink.reader.api.YueduApi - onHandlerError:
java.lang.IllegalStateException: DefaultData::class.java.…tor}$txtTocRuleFileName") must not be null
        at io.legado.app.help.DefaultData$txtTocRules$2.invoke(DefaultData.kt:13)
        at io.legado.app.help.DefaultData$txtTocRules$2.invoke(DefaultData.kt:9)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at io.legado.app.help.DefaultData.getTxtTocRules(DefaultData.kt)
        at io.legado.app.localBook.TextFile$Companion.getTocRules(TextFile.kt:263)
        at io.legado.app.localBook.TextFile$Companion.access$getTocRules(TextFile.kt:240)
        at io.legado.app.localBook.TextFile.analyze(TextFile.kt:30)
        at io.legado.app.localBook.LocalBook.getChapterList(LocalBook.kt:26)
        at org.lightink.reader.api.YueduApi.importBookPreview(YueduApi.kt:1592)
        at org.lightink.reader.api.YueduApi$initRouter$55.invokeSuspend(YueduApi.kt:237)
        at org.lightink.reader.api.YueduApi$initRouter$55.invoke(YueduApi.kt)
        at org.lightink.reader.verticle.RestVerticle$coroutineHandler$1$job$1.invokeSuspend(RestVerticle.kt:133)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
2022-04-16 16:58:49 [DefaultDispatcher-worker-2] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 0:0:0:0:0:0:0:1 - - [Sat, 16 Apr 2022 08:58:49 GMT] "POST /reader3/importBookPreview HTTP/1.1" 200 136 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"
2022-04-16 16:59:32 [vert.x-eventloop-thread-2] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 0:0:0:0:0:0:0:1 - - [Sat, 16 Apr 2022 08:59:32 GMT] "GET / HTTP/1.1" 200 4647 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"
2022-04-16 16:59:32 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - GET http://localhost:8080/reader3/getUserInfo
2022-04-16 16:59:32 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - request body:
2022-04-16 16:59:32 [DefaultDispatcher-worker-2] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 0:0:0:0:0:0:0:1 - - [Sat, 16 Apr 2022 08:59:32 GMT] "GET /reader3/getUserInfo HTTP/1.1" 200 74 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"
2022-04-16 16:59:32 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - GET http://localhost:8080/reader3/getBookshelf?refresh=0
2022-04-16 16:59:32 [vert.x-eventloop-thread-2] INFO  o.l.reader.verticle.RestVerticle - request body:
2022-04-16 16:59:32 [DefaultDispatcher-worker-3] INFO  org.lightink.reader.utils.VertExt - storage key: [data, default, bookshelf] path: F:\storage\data\default\bookshelf.json
2022-04-16 16:59:32 [DefaultDispatcher-worker-3] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 0:0:0:0:0:0:0:1 - - [Sat, 16 Apr 2022 08:59:32 GMT] "GET /reader3/getBookshelf?refresh=0 HTTP/1.1" 200 42 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"
2022-04-16 16:59:35 [vert.x-eventloop-thread-2] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 0:0:0:0:0:0:0:1 - - [Sat, 16 Apr 2022 08:59:35 GMT] "GET /service-worker.js HTTP/1.1" 304 0 "http://localhost:8080/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"

```

**Comment by hectorqin** [comment]
用11看看
