### ISSUE TITLE
看一段时间之后就报错

### ISSUE THREAD

**Issue by marujun** [hectorqin/reader#320]
```
[972d5d65] [DefaultDispatcher-worker-4] 09:58:40.482 ERROR Ext - 解析内容出错: io.vertx.core.json.DecodeException: Failed to decode:Unexpected character (':>
 at [Source: (StringReader); line: 1, column: 83690] (through reference chain: java.util.ArrayList[20])  内容:
[{"bookSourceUrl":"https://m.ahzwx.com","bookSourceName":"爱好中文","bookSourceGroup":"🔰普通","bookSourceType":0,"bookUrlPattern":null,"customOrder":-20859>
 at [Source: (StringReader); line: 1, column: 83690] (through reference chain: java.util.ArrayList[20])).cookie(\"PHPSESSID\");\n            token= java.get>
[972d5d65] [DefaultDispatcher-worker-4] 09:58:40.491 ERROR YueduApi - onHandlerError:
io.vertx.core.json.DecodeException: Failed to decode:Unexpected character (':' (code 58)): was expecting comma to separate Object entries
 at [Source: (StringReader); line: 1, column: 83690] (through reference chain: java.util.ArrayList[20])
        at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:97)
        at io.vertx.core.json.jackson.JacksonCodec.fromString(JacksonCodec.java:57)
        at io.vertx.core.json.JsonArray.fromJson(JsonArray.java:845)
        at io.vertx.core.json.JsonArray.<init>(JsonArray.java:54)
        at com.htmake.reader.utils.ExtKt.asJsonArray(Ext.kt:390)
        at com.htmake.reader.api.controller.BookSourceController.getUserBookSourceJson(BookSourceController.kt:82)
        at com.htmake.reader.api.controller.BookSourceController.getBookSources(BookSourceController.kt:222)
        at com.htmake.reader.api.YueduApi$initRouter$9.invokeSuspend(YueduApi.kt:183)
        at com.htmake.reader.api.YueduApi$initRouter$9.invoke(YueduApi.kt)
        at com.htmake.reader.api.YueduApi$initRouter$9.invoke(YueduApi.kt)
        at com.htmake.reader.verticle.RestVerticle$coroutineHandler$1$2.invokeSuspend(RestVerticle.kt:151)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character (':' (code 58)): was expecting comma to separate Object entries
 at [Source: (StringReader); line: 1, column: 83690] (through reference chain: java.util.ArrayList[20])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:302)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
        at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:95)
        ... 16 common frames omitted
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character (':' (code 58)): was expecting comma to separate Object entries
 at [Source: (StringReader); line: 1, column: 86188]
```

**Comment by marujun** [comment]
```
{
    "bookSourceComment": "//本网站有很多垃圾冗余无法净化\n//需专用字体才可正常显示\n//https://m.ah123z.com/",
    "bookSourceGroup": "🔰普通",
    "bookSourceName": "爱好中文",
    "bookSourceType": 0,
    "bookSourceUrl": "https://m.ahzwx.com",
    "customOrder": -2085959000,
    "enabled": true,
    "enabledCookieJar": true,
    "enabledExplore": true,
    "enabledReview": true,
    "exploreUrl": "月点击榜::/top/monthvisit_{{page}}/\n周点击榜::/top/weekvisit_{{page}}/\n总点击榜::/top/allvisit_{{page}}/\n最近更新::/top/lastupdate_{{page}}/\n最新入库::/top/postdate_{{page}}/\n总收藏榜::/top/goodnum_{{page}}/\n玄幻魔法::/sort/1_{{page}}/\n仙侠修真::/sort/2_{{page}}/\n都市言情::/sort/3_{{page}}/\n历史军事::/sort/4_{{page}}/\n网游小说::/sort/5_{{page}}/\n科幻小说::/sort/6_{{page}}/\n灵异小说::/sort/7_{{page}}/\n其他类型::/sort/8_{{page}}/\n完本小说::/full/{{page}}/",
    "lastUpdateTime": 1670302186887,
    "respondTime": 66782,
    "ruleBookInfo": {
      "author": "[property$=author]@content",
      "coverUrl": "[property$=image]@content",
      "init": "",
      "intro": "[property$=description]@content##(^|[。！？]+[”」）】]?)##$1<br>",
      "kind": ".xx li.1@text&&[property=\"og:novel:status\"]@content&&[property=\"og:novel:update_time\"]@content##分类.|小说|\\s.*",
      "lastChapter": "[property$=latest_chapter_name]@content##[\\(（【].*?[求更谢乐发订合补加].*?[】）\\)]",
      "name": "[property$=book_name]@content"
    },
    "ruleContent": {
      "content": "#nr@p@html",
      "imageStyle": "TEXT",
      "nextContentUrl": "text.下一页@href",
      "replaceRegex": "##\\-->|\\s*『章节错误.*』\\s*|\\s*『百度搜索.*』\\s*|\\s*（收藏.*）\\s*|\\s*.*百度搜索.*\\s*",
      "sourceRegex": ""
    },
    "ruleExplore": {
      "author": "a.2@text",
      "bookList": ".xbk",
      "bookUrl": "a.0@href",
      "coverUrl": "img@data-original",
      "intro": "span.2@text",
      "kind": ".tjrs@text",
      "lastChapter": "a.3@text",
      "name": "a.1@text"
    },
    "ruleReview": {},
    "ruleSearch": {
      "author": "a.2@text",
      "bookList": ".xbk li",
      "bookUrl": "a.1@href",
      "coverUrl": "a.1@href##.+\\D((\\d+)\\d{3})\\D##https://www.ah123z.com/files/article/image/$2/$1/$1s.jpg###",
      "kind": "a.0@text##\\[|\\]",
      "name": "a.1@text"
    },
    "ruleToc": {
      "chapterList": ".zxjz li a",
      "chapterName": "text##[\\(（【].*?[求更谢乐发订合补加].*?[】）\\)]",
      "chapterUrl": "href",
      "nextTocUrl": "text.下一页@href"
    },
    "searchUrl": "/s.php,{\n  \"charset\": \"gbk\",\n  \"method\": \"POST\",\n  \"body\": \"type=articlename&s={{key}}\"\n}",
    "weight": 0
  }
```
