### ISSUE TITLE
通过sh脚本启动出现这个情况如何解决？？

### ISSUE THREAD

**Issue by 3wlh** [hectorqin/reader#351]
12:51:49.892 [main] INFO com.htmake.reader.ReaderApplication - Starting application with args: [--reader.server.port=8082]
??????? ???????? ?????? ??????? ??????????????? 
????????????????????????????????????????????????
??????????????  ???????????  ?????????  ????????
??????????????  ???????????  ?????????  ????????
???  ??????????????  ??????????????????????  ???
???  ??????????????  ?????????? ???????????  ???

2023-04-11 12:51:50 [] [main] INFO  c.htmake.reader.ReaderApplicationKt - Starting ReaderApplicationKt on NAS_3wking with PID 6129 (/volume1/@appstore/Reader/bin/reader-pro-3.0.2.jar started by root in /)
2023-04-11 12:51:50 [] [main] DEBUG c.htmake.reader.ReaderApplicationKt - Running with Spring Boot v2.1.6.RELEASE, Spring v5.1.8.RELEASE
2023-04-11 12:51:50 [] [main] INFO  c.htmake.reader.ReaderApplicationKt - No active profile set, falling back to default profiles: default
2023-04-11 12:51:51 [] [vert.x-eventloop-thread-0] INFO  com.htmake.reader.api.YueduApi - port: 8080
2023-04-11 12:51:51 [] [vert.x-eventloop-thread-0] INFO  com.htmake.reader.api.YueduApi - serverPort: 8082
2023-04-11 12:51:51 [] [vert.x-eventloop-thread-0] INFO  com.htmake.reader.utils.Ext - osName: Linux currentDir: /
2023-04-11 12:51:51 [] [vert.x-eventloop-thread-0] INFO  com.htmake.reader.utils.Ext - Using workdir: /
2023-04-11 12:51:52 [] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - port: 8082
2023-04-11 12:51:52 [] [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService 'taskScheduler'
2023-04-11 12:51:52 [] [main] INFO  c.htmake.reader.ReaderApplicationKt - Started ReaderApplicationKt in 2.169 seconds (JVM running for 2.638)
2023-04-11 12:51:52 [] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - Server running at: http://localhost:8082
2023-04-11 12:51:52 [] [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - Web reader running at: http://localhost:8082
ReaderApplication Started
2023-04-11 12:52:23 [4dbabb0d] [vert.x-eventloop-thread-0] ERROR com.htmake.reader.utils.Ext - Internal Server Error
java.lang.RuntimeException: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /tmp/vertx-cache/file-cache-08734b92-8c82-4a18-a80a-f93407bfaac3/web/bg/???2.jpg
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.wrapInTCCLSwitch(StaticHandlerImpl.java:277)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.isFileExisting(StaticHandlerImpl.java:283)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.sendStatic(StaticHandlerImpl.java:192)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.handle(StaticHandlerImpl.java:145)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.handle(StaticHandlerImpl.java:51)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
	at io.vertx.ext.web.handler.impl.LoggerHandlerImpl.handle(LoggerHandlerImpl.java:171)
	at io.vertx.ext.web.handler.impl.LoggerHandlerImpl.handle(LoggerHandlerImpl.java:44)
	at com.htmake.reader.utils.VertExtKt.globalHandler$lambda-0(VertExt.kt:58)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.doEnd(BodyHandlerImpl.java:296)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl$BHandler.end(BodyHandlerImpl.java:276)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.lambda$handle$0(BodyHandlerImpl.java:87)
	at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:530)
	at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:516)
	at io.vertx.core.http.impl.Http1xServerConnection.handleEnd(Http1xServerConnection.java:176)
	at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:138)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:173)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:61)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /tmp/vertx-cache/file-cache-08734b92-8c82-4a18-a80a-f93407bfaac3/web/bg/???2.jpg
	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.io.File.toPath(File.java:2236)
	at io.vertx.core.file.impl.FileResolver.unpackFromJarURL(FileResolver.java:240)
	at io.vertx.core.file.impl.FileResolver.unpackUrlResource(FileResolver.java:158)
	at io.vertx.core.file.impl.FileResolver.resolveFile(FileResolver.java:139)
	at io.vertx.core.impl.VertxImpl.resolveFile(VertxImpl.java:805)
	at io.vertx.core.file.impl.FileSystemImpl$20.<init>(FileSystemImpl.java:933)
	at io.vertx.core.file.impl.FileSystemImpl.existsInternal(FileSystemImpl.java:932)
	at io.vertx.core.file.impl.FileSystemImpl.exists(FileSystemImpl.java:340)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$isFileExisting$2(StaticHandlerImpl.java:283)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.wrapInTCCLSwitch(StaticHandlerImpl.java:266)
	... 55 common frames omitted
2023-04-11 12:52:23 [4dbabb0d] [vert.x-eventloop-thread-0] ERROR com.htmake.reader.utils.Ext - {"error":"Internal Server Error","exception":"java.lang.RuntimeException: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /tmp/vertx-cache/file-cache-08734b92-8c82-4a18-a80a-f93407bfaac3/web/bg/???2.jpg","message":"java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /tmp/vertx-cache/file-cache-08734b92-8c82-4a18-a80a-f93407bfaac3/web/bg/???2.jpg","path":"http://10.10.10.252:8082/","status":500,"timestamp":1681188743773}
2023-04-11 12:52:23 [4dbabb0d] [vert.x-eventloop-thread-0] ERROR i.v.e.w.h.impl.LoggerHandlerImpl - 10.10.10.105 - - [Tue, 11 Apr 2023 04:52:23 GMT] "GET / HTTP/1.1" 500 521 "http://10.10.10.252:5000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.34"

**Comment by 3wking** [comment]
{"error":"Internal Server Error","exception":"java.lang.RuntimeException: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /tmp/vertx-cache/file-cache-c04f54fc-b1c9-479d-8b82-b0bc9bbc39c6/web/bg/羊皮纸2.jpg","message":"java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /tmp/vertx-cache/file-cache-c04f54fc-b1c9-479d-8b82-b0bc9bbc39c6/web/bg/羊皮纸2.jpg","path":"http://10.10.10.252:8082/","status":500,"timestamp":1681189882151}

**Comment by 3wking** [comment]
用命令能正常启动用脚本就不行，说 /tmp/vertx-cache/file-cache-c04f54fc-b1c9-479d-8b82-b0bc9bbc39c6/web/bg文件夹没有文件

**Comment by 3wking** [comment]
好像是没有这个文件 /tmp/vertx-cache/file-cache-c04f54fc-b1c9-479d-8b82-b0bc9bbc39c6/web/bg/羊皮纸2.jpg 重启后文件地址随机生成，如何固定这个文件地址
