### ISSUE TITLE
用jar包直接启动参数接受中文乱码

### ISSUE THREAD

**Issue by ZuiYue-JuSHi** [hectorqin/reader#374]
系统是windows，cmd编码和系统编码以及jdk环境都加过utf了，不管用。

Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('\' (code 92)): was expecting double-quote to start field name
 at [Source: (String)"[{"bookSourceUrl":"https://www.52shukuwang.com","bookSourceName":"52涔﹀簱(52shukuwang)","bookSourceGroup":"涔卞簭","bookSourceType":0,"bookUrlPattern":null,"customOrder":-2086085998,"enabled":true,"enabledExplore":true,"enabledCookieJar":false,"concurrentRate":null,"header":"{ \"User-Agent\": \"Mozilla/5.0 (Linux; Android 8.1.0; JKM-AL00b Build/HUAWEIJKM-AL00b; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/6.2 TBS/044807 Mobile Safari/537.36\"}","loginUrl":nul"[truncated 2844 chars]; line: 1, column: 660] (through reference chain: java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:302)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)

**Comment by ZuiYue-JuSHi** [comment]
解析出来的书源列表是正常的中文，导入后就乱码了
