### ISSUE TITLE
docker部署的导入书籍大于10兆出现问题，代码java.lang.NullPointerException

### ISSUE THREAD

**Issue by xbcui1975** [hectorqin/reader#45]
导入txt书籍报错（java.lang.NullPointerException）txt大小大概10多兆

**Comment by hectorqin** [comment]
提供一下详细日志

**Comment by xbcui1975** [comment]
2022-04-24 13:03:50 [main] INFO  c.htmake.reader.ReaderApplicationKt - Starting ReaderApplicationKt on 8aa7c1a5eb94 with PID 8 (/app/bin/reader.jar started by root in /)
2022-04-24 13:03:50 [main] DEBUG c.htmake.reader.ReaderApplicationKt - Running with Spring Boot v2.1.6.RELEASE, Spring v5.1.8.RELEASE
2022-04-24 13:03:50 [main] INFO  c.htmake.reader.ReaderApplicationKt - No active profile set, falling back to default profiles: default
2022-04-24 13:03:52 [vert.x-eventloop-thread-0] INFO  com.htmake.reader.api.YueduApi - port: 8080
2022-04-24 13:03:52 [vert.x-eventloop-thread-0] INFO  com.htmake.reader.api.YueduApi - serverPort: 8080
2022-04-24 13:03:53 [vert.x-eventloop-thread-0] INFO  com.htmake.reader.utils.VertExt - osName: Linux currentDir: /
2022-04-24 13:03:53 [vert.x-eventloop-thread-0] INFO  com.htmake.reader.utils.VertExt - storage key: [cache, invalidBookSourceList] path: /storage/cache/invalidBookSourceList.json
2022-04-24 13:03:53 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - port: 8080
2022-04-24 13:03:53 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService 'taskScheduler'
2022-04-24 13:03:53 [main] INFO  c.htmake.reader.ReaderApplicationKt - Started ReaderApplicationKt in 4.412 seconds (JVM running for 5.79)
2022-04-24 13:03:53 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - Server running at: http://localhost:8080
2022-04-24 13:03:53 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - Web reader running at: http://localhost:8080
2022-04-24 13:04:26 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 10.0.3.1 - - [Sun, 24 Apr 2022 05:04:26 GMT] "GET / HTTP/1.1" 200 4647 "-" "python-requests/2.25.0"
2022-04-24 13:04:30 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:30 GMT] "GET / HTTP/1.1" 200 4647 "http://192.168.0.104:2633/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:30 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:30 GMT] "GET /css/app.0dccd3ad.css HTTP/1.1" 200 4916 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:30 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:30 GMT] "GET /css/chunk-vendors.0382860f.css HTTP/1.1" 200 117149 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:30 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:30 GMT] "GET /js/app.c50693cc.js HTTP/1.1" 200 58779 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:30 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:30 GMT] "GET /js/chunk-vendors.b51465d7.js HTTP/1.1" 200 674414 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:30 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:30 GMT] "GET /css/index.ad25e252.css HTTP/1.1" 200 26695 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:30 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:30 GMT] "GET /css/reader.0f4efb18.css HTTP/1.1" 200 34079 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:30 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:30 GMT] "GET /js/index.fa26992f.js HTTP/1.1" 200 121040 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:30 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:30 GMT] "GET /js/reader.ae47874b.js HTTP/1.1" 200 86923 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:30 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://192.168.0.104:1234/reader3/getUserInfo
2022-04-24 13:04:30 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - request body: 
2022-04-24 13:04:30 [DefaultDispatcher-worker-2] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:30 GMT] "GET /reader3/getUserInfo HTTP/1.1" 200 74 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:31 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:31 GMT] "GET /assets/reader.css HTTP/1.1" 200 54 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:31 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://192.168.0.104:1234/reader3/getBookshelf?refresh=0
2022-04-24 13:04:31 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - request body: 
2022-04-24 13:04:31 [DefaultDispatcher-worker-2] INFO  com.htmake.reader.utils.VertExt - storage key: [data, default, bookshelf] path: /storage/data/default/bookshelf.json
2022-04-24 13:04:31 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:31 GMT] "GET /fonts/element-icons.535877f5.woff HTTP/1.1" 200 28200 "http://192.168.0.104:1234/css/chunk-vendors.0382860f.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:31 [DefaultDispatcher-worker-2] INFO  com.htmake.reader.utils.VertExt - storage key: [data, default, bookSource] path: /storage/data/default/bookSource.json
2022-04-24 13:04:32 [DefaultDispatcher-worker-3] INFO  c.h.r.api.controller.BaseController - Loop: 1 concurrentCount: 16 lastIndex: 28 endIndex: 33 costTime: 651 ms deferredList size: 10
2022-04-24 13:04:32 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:32 GMT] "GET /img/icons/favicon-32x32.png HTTP/1.1" 200 1680 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:32 [DefaultDispatcher-worker-3] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:31 GMT] "GET /reader3/getBookshelf?refresh=0 HTTP/1.1" 200 25899 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:32 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:32 GMT] "GET /img/noCover.b5c48bc1.jpeg HTTP/1.1" 200 5959 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:32 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://192.168.0.104:1234/reader3/getSources?simple=1
2022-04-24 13:04:32 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - request body: 
2022-04-24 13:04:32 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://192.168.0.104:1234/reader3/getBookGroups
2022-04-24 13:04:32 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - request body: 
2022-04-24 13:04:32 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - GET http://192.168.0.104:1234/reader3/getRssSources?simple=1
2022-04-24 13:04:32 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - request body: 
2022-04-24 13:04:32 [DefaultDispatcher-worker-3] INFO  com.htmake.reader.utils.VertExt - storage key: [data, default, bookSource] path: /storage/data/default/bookSource.json
2022-04-24 13:04:32 [DefaultDispatcher-worker-3] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:32 GMT] "GET /reader3/getSources?simple=1 HTTP/1.1" 200 42 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:32 [DefaultDispatcher-worker-3] INFO  com.htmake.reader.utils.VertExt - storage key: [data, default, bookGroup] path: /storage/data/default/bookGroup.json
2022-04-24 13:04:32 [DefaultDispatcher-worker-5] INFO  com.htmake.reader.utils.VertExt - storage key: [data, default, rssSources] path: /storage/data/default/rssSources.json
2022-04-24 13:04:32 [DefaultDispatcher-worker-3] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:32 GMT] "GET /reader3/getBookGroups HTTP/1.1" 200 104 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:32 [DefaultDispatcher-worker-5] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:32 GMT] "GET /reader3/getRssSources?simple=1 HTTP/1.1" 200 42 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"
2022-04-24 13:04:36 [vert.x-eventloop-thread-0] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 10.0.3.1 - - [Sun, 24 Apr 2022 05:04:36 GMT] "GET / HTTP/1.1" 200 4647 "-" "python-requests/2.25.0"
2022-04-24 13:04:44 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - POST http://192.168.0.104:1234/reader3/importBookPreview
2022-04-24 13:04:44 [vert.x-eventloop-thread-0] INFO  c.h.reader.verticle.RestVerticle - request body: 
2022-04-24 13:04:44 [DefaultDispatcher-worker-3] INFO  c.h.r.api.controller.BookController - uploadFile: file-uploads/16ad8e1c-8250-4034-a65d-5ef7684388d4 都市奇缘（未删节1-2910章）作者：易天下.txt file-uploads/16ad8e1c-8250-4034-a65d-5ef7684388d4
2022-04-24 13:04:44 [DefaultDispatcher-worker-3] INFO  c.h.r.api.controller.BookController - moveTo: storage/assets/default/book/都市奇缘（未删节1-2910章）作者：易天下.txt
2022-04-24 13:04:47 [DefaultDispatcher-worker-3] ERROR com.htmake.reader.api.YueduApi - onHandlerError: 
java.lang.NullPointerException: null
        at io.legado.app.localBook.TextFile.analyze(TextFile.kt:116)
        at io.legado.app.localBook.TextFile.analyze(TextFile.kt:92)
        at io.legado.app.localBook.TextFile.analyze(TextFile.kt:92)
        at io.legado.app.localBook.TextFile.analyze(TextFile.kt:92)
        at io.legado.app.localBook.TextFile.analyze(TextFile.kt:92)
        at io.legado.app.localBook.TextFile.analyze(TextFile.kt:92)
        at io.legado.app.localBook.TextFile.analyze(TextFile.kt:35)
        at io.legado.app.localBook.LocalBook.getChapterList(LocalBook.kt:26)
        at com.htmake.reader.api.controller.BookController.importBookPreview(BookController.kt:202)
        at com.htmake.reader.api.YueduApi$initRouter$40.invokeSuspend(YueduApi.kt:207)
        at com.htmake.reader.api.YueduApi$initRouter$40.invoke(YueduApi.kt)
        at com.htmake.reader.api.YueduApi$initRouter$40.invoke(YueduApi.kt)
        at com.htmake.reader.verticle.RestVerticle$coroutineHandler$1$job$1.invokeSuspend(RestVerticle.kt:133)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
2022-04-24 13:04:47 [DefaultDispatcher-worker-3] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 192.168.0.100 - - [Sun, 24 Apr 2022 05:04:44 GMT] "POST /reader3/importBookPreview HTTP/1.1" 200 63 "http://192.168.0.104:1234/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50"

**Comment by hectorqin** [comment]
阅读App能正常导入吗？提供一下小说文件

**Comment by xbcui1975** [comment]
[都市奇缘（未删节1-2910章）作者：易天下.txt](https://github.com/hectorqin/reader/files/8549281/1-2910.txt)没有试过app，app都是在线看wang'l网络小说

**Comment by hectorqin** [comment]
beta版更新了内核，现在不会报错，但是章节分割还是有问题

**Comment by xbcui1975** [comment]
> beta版更新了内核，现在不会报错，但是章节分割还是有问题

谢谢，能导入了
