### ISSUE TITLE
导入备份时提示导入成功，但实际没成功，而且有很多红色错误提示

### ISSUE THREAD

**Issue by vaysalee** [hectorqin/reader#586]
导入备份时提示导入成功，但实际没成功，而且有很多红色错误提示

版本：reader-pro-3.2.10.jar

错误提示：
1、WEB 界面：

2、CMD界面：

2024-09-01 10:05:34 [dca39c4c] [DefaultDispatcher-worker-1] ERROR com.htmake.reader.api.YueduApi - onHandlerError:
io.vertx.core.json.DecodeException: Failed to decode:Unexpected character ('\' (code 92)): was expecting double-quote to start field name
 at [Source: (StringReader); line: 13, column: 19] (through reference chain: java.util.ArrayList[0])
        at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:97)
        at io.vertx.core.json.jackson.JacksonCodec.fromString(JacksonCodec.java:57)
        at io.vertx.core.json.JsonArray.fromJson(JsonArray.java:845)
        at io.vertx.core.json.JsonArray.<init>(JsonArray.java:54)
        at com.htmake.reader.utils.ExtKt.asJsonArray(Ext.kt:545)
        at com.htmake.reader.api.controller.BookSourceController.getUserBookSourceJson(BookSourceController.kt:86)
        at com.htmake.reader.api.controller.BookSourceController.getBookSources(BookSourceController.kt:275)
        at com.htmake.reader.api.YueduApi$initRouter$11.invokeSuspend(YueduApi.kt:168)
        at com.htmake.reader.api.YueduApi$initRouter$11.invoke(YueduApi.kt)
        at com.htmake.reader.api.YueduApi$initRouter$11.invoke(YueduApi.kt)
        at com.htmake.reader.verticle.RestVerticle$coroutineHandler$1$2.invokeSuspend(RestVerticle.kt:163)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('\' (code 92)): was expecting double-quote to start field name
 at [Source: (StringReader); line: 13, column: 19] (through reference chain: java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:302)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
        at io.vertx.core.json.jackson.JacksonCodec.fromParser(JacksonCodec.java:95)
        ... 16 common frames omitted
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('\' (code 92)): was expecting double-quote to start field name
 at [Source: (StringReader); line: 13, column: 2196]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:693)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:591)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddName(ReaderBasedJsonParser.java:1767)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:917)
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.mapObject(UntypedObjectDeserializer.java:896)
        at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:654)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
        ... 21 common frames omitted
2024-09-01 10:05:34 [dca39c4c] [DefaultDispatcher-worker-1] INFO  i.v.e.w.h.impl.LoggerHandlerImpl - 0:0:0:0:0:0:0:1 - - [Sun, 1 Sep 2024 02:05:31 GMT] "GET /reader3/getBookSources?simple=1&v=1725156331504 HTTP/1.1" 200 273 "http://localhost:8080/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0"

**Comment by vaysalee** [comment]
WEB 界面：
![数据解析问题](https://github.com/user-attachments/assets/9ba250f3-b516-4afb-888d-3fb26166c63e)

**Comment by hectorqin** [comment]
书源文件有问题
